### ISSUE TITLE
Doc: Specify Python 3.7 in README.md python badge

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/bridge-in-tech-backend#213] opened 2021-03-10 22:10 UTC
### Is your feature request related to a problem? Please describe.
Most contributors face issue running application on python 3.8 and later related to the time.clock(). This is because the time.clock() module has been deprecated from v3.8.

### Describe the solution you'd like
Specify the python version to be used on the README.md python badge so that contributors will use the same.

### Describe alternatives you've considered
NA

### Additional context
NA

**Comment by dcs-soni** [comment] 2021-03-13 09:47
Hi. I would like to work on this issue.

**Comment by mtreacy002** [comment] 2021-03-13 12:58
Sure, @dcs-soni , I'll assign you to this. Thanks for picking up the issue 😉.

**Comment by epicadk** [comment] 2021-03-13 13:30
@mtreacy002 I can't replicate the issue. It works just fine for me on python 3.9.1. Can you provide steps to reproduce?

**Comment by epicadk** [comment] 2021-03-14 16:01
> @mtreacy002 I can't replicate the issue. It works just fine for me on python 3.9.1. Can you provide steps to reproduce?

@vj-codes can you confirm this?

**Comment by mtreacy002** [comment] 2021-03-14 23:53
@epicadk , I believe there are a couple of people facing issue with time.clock() module that was deprecated from Python v3.8 and above. On Zulip you can search `time.clock()` and see the discussions on this ([here's](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/Get.20started/near/212041534) on of them). I'm currently on Python 3.7.9 so can't really replicate the issue, but I'm wondering how this is not affecting you or @vj-codes on v3.9 but affecting some others (the issue was fixed when they downgraded to Python 3.7)? How do we find out the real culprit here 🤔

**Comment by devkapilbansal** [comment] 2021-03-16 12:09
@epicadk @mtreacy002 I am not able to use `time.clock` even on python 3.9

![time](https://user-images.githubusercontent.com/42766576/111306708-90e72200-867e-11eb-8d9b-a77b6edf6bd5.png)

**Comment by epicadk** [comment] 2021-03-16 12:17
> @epicadk @mtreacy002 I am not able to use `time.clock` even on python 3.9
> 
> ![time](https://user-images.githubusercontent.com/42766576/111306708-90e72200-867e-11eb-8d9b-a77b6edf6bd5.png)

Yes it was removed in python 3.8 so this is expected however I don't know why I don't get the error on the latest version of python

**Comment by vj-codes** [comment] 2021-03-16 12:43
@mtreacy002 you had asked me earlier also but I have no idea why it worked for me. 
Now that Aditya also confirms it's working for him and the only thing I see common is both of us had  already setup ms-backend first while other contributors do the other way. 

Also as far as I remember I didn't refractor any code for time clock on 3.9 it just simply worked @epicadk did you change anything?

**Comment by epicadk** [comment] 2021-03-16 12:52
> @mtreacy002 you had asked me earlier also but I have no idea why it worked for me.
> Now that Aditya also confirms it's working for him and the only thing I see common is both of us had already setup ms-backend first while other contributors do the other way.
> 
> Also as far as I remember I didn't refractor any code for time clock on 3.9 it just simply worked @epicadk did you change anything?

Nope it worked. Kapil can you try running bit on python 3.9. I think it should work. I don't see where we have used `time.clock()` in the project, is it an external library that uses `time.clock()`?

**Comment by devkapilbansal** [comment] 2021-03-16 20:15
Point 4 [here](https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals) mentions that `time.clock()` is deprecated from `python 3.3`. Instead of making changes in doc, I would like to suggest making changes in the code itself.

**Comment by devkapilbansal** [comment] 2021-03-16 20:40
@mtreacy002 @epicadk @vj-codes after clearly going through the issue, I came to know that this was not an issue with this repository code but with a dependency. The dependency has been upgraded already. AFAIK. :thinking: 
Contributors need to update the dependency i.e. `sqlalchemy` to fix the error

**Comment by mtreacy002** [comment] 2021-03-18 01:41
@devkapilbansal , can you tell me the SQLALchemy version number you used to fix this? My old dependencies installation on MacOS has SQLAlchemy 1.3.20. But my latest dependencies installation (this month)  on Windows 10 has SQLAlchemy 1.3.23. Is this the right version for the bug?
PS: I had both machines running Python v 3.7.9 though so I couldn't tell 😁

**Comment by epicadk** [comment] 2021-03-20 04:18
@mtreacy002 are you sure about this? Because the app works fine for a lot of contributors on python 3.9?

**Comment by mtreacy002** [comment] 2021-03-20 09:18
@epicadk , it doesn't hurt to state it as 3.7 as there are contributors facing issue with this. Also, on gh-actions/travis we're even using python 3.6. If the contributors do face issues during installation, they can check the python version that known to work without issue (through checking the python badge on README) and try to downgrade to that. 
We can investigate this further by opening an issue to find alternative solution for time.clock() error for those on python 3.8 or later (perhaps by trying @devkapilbansal's suggestion, updating SQLAlchemy  and mention it on README.md if that fixes the issue).

**Comment by devkapilbansal** [comment] 2021-03-23 05:45
@mtreacy002 this was fixed in some version after 1.13.15 however I am not able to trace it back. The exact ticket for this was:-
https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1319/

Also, none of your dependencies should be infected by this issue. Both versions `1.13.20` and version `1.13.23` are free from this.

**Comment by mtreacy002** [comment] 2021-03-23 22:41
Thanks, @devkapilbansal for the info. We can check this out when the next contributor is facing the time.closk() issue during setup.

**Closed as completed** 2021-04-05 03:49 UTC
Labels: Category: Documentation/Training, First Timers Only, Type: Maintenance
